/** Page Actions */
const UPDATE_PAGE_NAME = 'UPDATE_PAGE_NAME_TYPE';
const UPDATE_DETAILS_PAGE_NAME = 'UPDATE_DETAILS_PAGE_NAME_TYPE';
const SHOW_BOTTOM_VIEW = 'SHOW_BOTTOM_VIEW_TYPE';
const HIDE_BOTTOM_VIEW = 'HIDE_BOTTOM_VIEW_TYPE';

export default {
	UPDATE_PAGE_NAME,
	UPDATE_DETAILS_PAGE_NAME
};
