/** Page Actions */
const UPDATE_PAGE_NAME = 'UPDATE_PAGE_NAME_TYPE';
const UPDATE_DETAILS_PAGE_NAME = 'UPDATE_DETAILS_PAGE_NAME_TYPE';

export default {
	UPDATE_PAGE_NAME,
	UPDATE_DETAILS_PAGE_NAME
};
